/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderNewRouteImport } from './routes/order/new'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNewRoute = OrderNewRouteImport.update({
  id: '/order/new',
  path: '/order/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchants': typeof MerchantsRoute
  '/orders': typeof OrdersRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/order/new': typeof OrderNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchants': typeof MerchantsRoute
  '/orders': typeof OrdersRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/order/new': typeof OrderNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchants': typeof MerchantsRoute
  '/orders': typeof OrdersRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/order/new': typeof OrderNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merchants'
    | '/orders'
    | '/sign-in'
    | '/sign-up'
    | '/order/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/merchants' | '/orders' | '/sign-in' | '/sign-up' | '/order/new'
  id:
    | '__root__'
    | '/'
    | '/merchants'
    | '/orders'
    | '/sign-in'
    | '/sign-up'
    | '/order/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchantsRoute: typeof MerchantsRoute
  OrdersRoute: typeof OrdersRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  OrderNewRoute: typeof OrderNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/new': {
      id: '/order/new'
      path: '/order/new'
      fullPath: '/order/new'
      preLoaderRoute: typeof OrderNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchantsRoute: MerchantsRoute,
  OrdersRoute: OrdersRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  OrderNewRoute: OrderNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
