/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRiderRouteImport } from './routes/_authenticated/rider'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMerchantSetupRouteImport } from './routes/_authenticated/merchant-setup'
import { Route as AuthenticatedMerchantRouteImport } from './routes/_authenticated/merchant'
import { Route as AuthenticatedOrderNewRouteImport } from './routes/_authenticated/order/new'
import { Route as AuthenticatedMerchantPricingRouteImport } from './routes/_authenticated/merchant/pricing'
import { Route as AuthenticatedMerchantOverviewRouteImport } from './routes/_authenticated/merchant/overview'
import { Route as AuthenticatedMerchantInventoryRouteImport } from './routes/_authenticated/merchant/inventory'
import { Route as AuthenticatedMerchantHeatmapRouteImport } from './routes/_authenticated/merchant/heatmap'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiderRoute = AuthenticatedRiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMerchantSetupRoute =
  AuthenticatedMerchantSetupRouteImport.update({
    id: '/merchant-setup',
    path: '/merchant-setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMerchantRoute = AuthenticatedMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrderNewRoute = AuthenticatedOrderNewRouteImport.update({
  id: '/order/new',
  path: '/order/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMerchantPricingRoute =
  AuthenticatedMerchantPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantOverviewRoute =
  AuthenticatedMerchantOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantInventoryRoute =
  AuthenticatedMerchantInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantHeatmapRoute =
  AuthenticatedMerchantHeatmapRouteImport.update({
    id: '/heatmap',
    path: '/heatmap',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchants': typeof MerchantsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/merchant': typeof AuthenticatedMerchantRouteWithChildren
  '/merchant-setup': typeof AuthenticatedMerchantSetupRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/merchant/heatmap': typeof AuthenticatedMerchantHeatmapRoute
  '/merchant/inventory': typeof AuthenticatedMerchantInventoryRoute
  '/merchant/overview': typeof AuthenticatedMerchantOverviewRoute
  '/merchant/pricing': typeof AuthenticatedMerchantPricingRoute
  '/order/new': typeof AuthenticatedOrderNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchants': typeof MerchantsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/merchant': typeof AuthenticatedMerchantRouteWithChildren
  '/merchant-setup': typeof AuthenticatedMerchantSetupRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/merchant/heatmap': typeof AuthenticatedMerchantHeatmapRoute
  '/merchant/inventory': typeof AuthenticatedMerchantInventoryRoute
  '/merchant/overview': typeof AuthenticatedMerchantOverviewRoute
  '/merchant/pricing': typeof AuthenticatedMerchantPricingRoute
  '/order/new': typeof AuthenticatedOrderNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/merchants': typeof MerchantsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/merchant': typeof AuthenticatedMerchantRouteWithChildren
  '/_authenticated/merchant-setup': typeof AuthenticatedMerchantSetupRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rider': typeof AuthenticatedRiderRoute
  '/_authenticated/merchant/heatmap': typeof AuthenticatedMerchantHeatmapRoute
  '/_authenticated/merchant/inventory': typeof AuthenticatedMerchantInventoryRoute
  '/_authenticated/merchant/overview': typeof AuthenticatedMerchantOverviewRoute
  '/_authenticated/merchant/pricing': typeof AuthenticatedMerchantPricingRoute
  '/_authenticated/order/new': typeof AuthenticatedOrderNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merchants'
    | '/sign-in'
    | '/sign-up'
    | '/merchant'
    | '/merchant-setup'
    | '/orders'
    | '/profile'
    | '/rider'
    | '/merchant/heatmap'
    | '/merchant/inventory'
    | '/merchant/overview'
    | '/merchant/pricing'
    | '/order/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/merchants'
    | '/sign-in'
    | '/sign-up'
    | '/merchant'
    | '/merchant-setup'
    | '/orders'
    | '/profile'
    | '/rider'
    | '/merchant/heatmap'
    | '/merchant/inventory'
    | '/merchant/overview'
    | '/merchant/pricing'
    | '/order/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/merchants'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/merchant'
    | '/_authenticated/merchant-setup'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/rider'
    | '/_authenticated/merchant/heatmap'
    | '/_authenticated/merchant/inventory'
    | '/_authenticated/merchant/overview'
    | '/_authenticated/merchant/pricing'
    | '/_authenticated/order/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  MerchantsRoute: typeof MerchantsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rider': {
      id: '/_authenticated/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof AuthenticatedRiderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchant-setup': {
      id: '/_authenticated/merchant-setup'
      path: '/merchant-setup'
      fullPath: '/merchant-setup'
      preLoaderRoute: typeof AuthenticatedMerchantSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchant': {
      id: '/_authenticated/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof AuthenticatedMerchantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order/new': {
      id: '/_authenticated/order/new'
      path: '/order/new'
      fullPath: '/order/new'
      preLoaderRoute: typeof AuthenticatedOrderNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchant/pricing': {
      id: '/_authenticated/merchant/pricing'
      path: '/pricing'
      fullPath: '/merchant/pricing'
      preLoaderRoute: typeof AuthenticatedMerchantPricingRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/overview': {
      id: '/_authenticated/merchant/overview'
      path: '/overview'
      fullPath: '/merchant/overview'
      preLoaderRoute: typeof AuthenticatedMerchantOverviewRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/inventory': {
      id: '/_authenticated/merchant/inventory'
      path: '/inventory'
      fullPath: '/merchant/inventory'
      preLoaderRoute: typeof AuthenticatedMerchantInventoryRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/heatmap': {
      id: '/_authenticated/merchant/heatmap'
      path: '/heatmap'
      fullPath: '/merchant/heatmap'
      preLoaderRoute: typeof AuthenticatedMerchantHeatmapRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
  }
}

interface AuthenticatedMerchantRouteChildren {
  AuthenticatedMerchantHeatmapRoute: typeof AuthenticatedMerchantHeatmapRoute
  AuthenticatedMerchantInventoryRoute: typeof AuthenticatedMerchantInventoryRoute
  AuthenticatedMerchantOverviewRoute: typeof AuthenticatedMerchantOverviewRoute
  AuthenticatedMerchantPricingRoute: typeof AuthenticatedMerchantPricingRoute
}

const AuthenticatedMerchantRouteChildren: AuthenticatedMerchantRouteChildren = {
  AuthenticatedMerchantHeatmapRoute: AuthenticatedMerchantHeatmapRoute,
  AuthenticatedMerchantInventoryRoute: AuthenticatedMerchantInventoryRoute,
  AuthenticatedMerchantOverviewRoute: AuthenticatedMerchantOverviewRoute,
  AuthenticatedMerchantPricingRoute: AuthenticatedMerchantPricingRoute,
}

const AuthenticatedMerchantRouteWithChildren =
  AuthenticatedMerchantRoute._addFileChildren(
    AuthenticatedMerchantRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedMerchantRoute: typeof AuthenticatedMerchantRouteWithChildren
  AuthenticatedMerchantSetupRoute: typeof AuthenticatedMerchantSetupRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRiderRoute: typeof AuthenticatedRiderRoute
  AuthenticatedOrderNewRoute: typeof AuthenticatedOrderNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMerchantRoute: AuthenticatedMerchantRouteWithChildren,
  AuthenticatedMerchantSetupRoute: AuthenticatedMerchantSetupRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRiderRoute: AuthenticatedRiderRoute,
  AuthenticatedOrderNewRoute: AuthenticatedOrderNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  MerchantsRoute: MerchantsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
